"""Dynamic rates — the pet's appetite tracks how hard you have been working.

THE TRAP THIS DESIGN EXISTS TO AVOID. The obvious reading of "make earning and
hunger both scale with usage" is a no-op, and provably so. If income scales as
usage^a and upkeep as usage^b off the same quantity, the player's slack goes as
usage^(1+a-b); the naive version is a=0, b=1, which is exactly the invariant
case. Simulated over 60 days at 0.25x, 1x and 4x usage it gives slack 7.40,
7.40, 7.40 — identical. Worse than useless: today's game already gives a heavy
user 16x the slack of a light one, so the naive feature's only real effect
would be to DELETE that difference and flatten the game.

The escape is not a cleverer exponent. It is that the two rates key off
quantities with different TIME CONSTANTS:

    earning  <- today's actual tokens
    appetite <- the trailing 7-day average

They cannot cancel because they are not measuring the same thing. The player's
daily position is today against their own recent average, which is precisely
the "one-up yourself" loop this mechanic exists to create, and it survives any
later retuning of the exponents.

THE FREE LUNCH. Measured on real usage history, today exceeds its own
trailing 7-day mean on only 29% of days — usage is heavily right-skewed. So a
"pace" readout sits below 100% about seven days in ten with no mechanical
cruelty at all. The feeling of being slightly behind is generated by the shape
of real work, not by a punishment.

ASYMMETRY IS DELIBERATE. Earning only ever moves up from the published base
(E_MIN = 1.0); appetite moves both ways. Letting a light user's conversion rate
fall BELOW the advertised 500 T/BIT would punish a new player for the first
week of getting started, so it is forbidden: the published rate is the worst it
ever gets.
"""
from __future__ import annotations

import math
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone

from ..config import BITS_RATIO

# ── Shape ───────────────────────────────────────────────────────────────────
EARN_EXP = 0.35          # earning rises with intensity, gently
DRAIN_EXP = 0.55         # appetite rises faster, but from a lower floor

EARN_MIN, EARN_MAX = 1.00, 3.00
DRAIN_MIN, DRAIN_MAX = 0.40, 2.00

SLEW = 1.25              # max +/-25% per 6h period
WINDOW_DAYS = 7
HISTORY_CAP = 28
PERIOD_HOURS = 6
CALIBRATION_DAYS = 2     # below this, both multipliers are pinned to 1.0
REST_HOURS = 48          # total silence for this long and the pet stops eating

# The pet's base appetite: a full bar in 3 hours of SESSION time at 1.0x.
#
# THE UNIT IS WHY THE NUMBER CAN BE THIS BRUTAL. Hunger accrues only while the
# window is open, and an open window means someone is at the desk — so three
# hours is three hours of actual work, not three hours of being asleep. On a
# wall clock the bar would have to outlast a night's sleep and the ceiling
# would be pinned by that instead. Closing the app pauses the pet completely.
#
# The clamp band therefore spans 1h30 (at 2.0x) to 7h30 (at 0.4x) of session
# time. DRAIN_MAX is set by the shortest bar that is still playable, not chosen
# for taste.
DRAIN_BASE_PER_6H = 200.0

# Usage at which both multipliers are exactly 1.0. DERIVED, not chosen: it is
# the usage at which the base economy breaks even, so one pivot serves both
# curves and cannot drift out of sync when a constant moves.
#
# THE DERIVATION HAS TO KNOW THAT THE PET ONLY EATS WHILE THE APP IS OPEN.
# Multiplying the 6h drain by four assumes a 24h day, which only holds on a
# wall clock; against session-time decay it puts U_REF at 239,520 tokens/day —
# so a genuinely heavy 193k/day average scores BELOW reference and earns no
# bonus at all, which is backwards. Upkeep is a function of hours the window is
# open, not hours in the day.
HUNGER_PER_BIT = 1.67
SESSION_HOURS_PER_DAY = 8.0     # a working day at the desk, app open
U_REF = ((DRAIN_BASE_PER_6H / PERIOD_HOURS) * SESSION_HOURS_PER_DAY
         / HUNGER_PER_BIT) * BITS_RATIO                    # ~80,000


@dataclass(frozen=True)
class Rates:
    earn: float
    drain: float
    intensity: float
    baseline: float
    resting: bool
    calibrating: bool

    def tokens_per_bit(self) -> int:
        """What the main-screen readout shows. Always an honest figure — the
        remainder is banked, so this is the real price, not an average."""
        return max(1, int(round(BITS_RATIO / self.earn)))


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


def day_key(when: datetime) -> str:
    return when.astimezone(timezone.utc).strftime("%Y-%m-%d")


def period_start(when: datetime) -> datetime:
    """The 00/06/12/18 slot boundary containing `when`.

    FIXED SLOTS, not "six hours since the last update". Deterministic across
    restarts, and two launches inside one slot cannot both fire a recompute.
    """
    local = when.astimezone()
    floored = local.replace(minute=0, second=0, microsecond=0,
                            hour=(local.hour // PERIOD_HOURS) * PERIOD_HOURS)
    return floored.astimezone(timezone.utc)


def baseline_tokens_per_day(history, now: datetime) -> tuple[float, int]:
    """Mean daily output tokens over the trailing window.

    Returns (mean, observed_days). A missing date inside the window counts as
    a real zero, not as missing data: someone who works two days a week has a
    genuinely low baseline and a genuinely cheap pet, which is correct.

    THE OFF-BY-ONE, worth stating because it is easy to reintroduce. Today
    occupies one of the seven slots. Summing seven COMPLETED days plus today
    over a denominator of seven inflates the baseline by 1/7 permanently — a
    steady 48k/day user would sit at intensity 1.14 forever instead of 1.00.
    Six completed days plus today.
    """
    today = day_key(now)
    wanted = {day_key(now - timedelta(days=i)) for i in range(WINDOW_DAYS)}
    total = 0.0
    seen = 0
    for row in history:
        if row.date in wanted:
            total += row.output_tokens
            if row.date != today or row.output_tokens > 0:
                seen += 1
    return total / WINDOW_DAYS, seen


def _slew_then_clamp(target: float, previous: float,
                     lo: float, hi: float) -> float:
    """Rate-limit, THEN bound. Order matters.

    Clamping first lets the subsequent slew step carry the value straight back
    outside the legal range.
    """
    stepped = max(previous / SLEW, min(previous * SLEW, target))
    return max(lo, min(hi, stepped))


def compute(history, prev_earn: float, prev_drain: float,
            last_token_at, now: datetime) -> Rates:
    """The whole rule, in one pure function so it can be tested without a game."""
    baseline, observed = baseline_tokens_per_day(history, now)

    if observed < CALIBRATION_DAYS:
        # A brand-new player must not be handed floor rates because their
        # history is empty. Nothing is scaled until there is something to
        # scale against, and the UI says so.
        return Rates(1.0, 1.0, 1.0, baseline, False, True)

    resting = (last_token_at is not None
               and (now - last_token_at) >= timedelta(hours=REST_HOURS))

    intensity = max(0.0, baseline / U_REF)
    earn_target = 1.0 if intensity <= 0 else intensity ** EARN_EXP
    drain_target = 1.0 if intensity <= 0 else intensity ** DRAIN_EXP

    if resting:
        # Two days of total silence means the pet is not hungry. Applied with
        # NO slew, because a mercy rule that takes a day to arrive is not one.
        drain = DRAIN_MIN
        # Earning must still DECAY toward neutral, and with the slew. Freezing
        # it is a clean exploit: rest a fortnight, come back to a zero baseline
        # holding a 2.5x earn multiplier.
        earn = _slew_then_clamp(1.0, prev_earn, EARN_MIN, EARN_MAX)
    else:
        earn = _slew_then_clamp(earn_target, prev_earn, EARN_MIN, EARN_MAX)
        drain = _slew_then_clamp(drain_target, prev_drain, DRAIN_MIN, DRAIN_MAX)

    return Rates(earn, drain, intensity, baseline, resting, False)


def pace(history, now: datetime) -> float | None:
    """Today's tokens as a fraction of the trailing baseline.

    This is the "feeling behind" surface, and it is honest: it reads below 1.0
    on ~71% of real days purely because usage is right-skewed.
    """
    baseline, observed = baseline_tokens_per_day(history, now)
    if observed < CALIBRATION_DAYS or baseline <= 0:
        return None
    today = day_key(now)
    got = next((r.output_tokens for r in history if r.date == today), 0)
    return got / baseline


def hours_to_empty(hunger: float, drain_mult: float) -> float:
    """For the detail view. Not used to make decisions, only to report."""
    per_hour = (DRAIN_BASE_PER_6H / PERIOD_HOURS) * max(0.01, drain_mult)
    return max(0.0, hunger) / per_hour if per_hour > 0 else math.inf
